### PR TITLE
fix: update path to main file in package.json. Fixes #192

### LINKED ISSUE #192: v2.0.0-beta.12: Cannot find module <...>/node_modules/zod/[]]./lib/src/index.js'.
After upgrading to `v2.0.0-beta.12` I started getting the following error:

```
Cannot find module <...>/node_modules/zod/[]]./lib/src/index.js'.
```

Caused by this line:
https://github.com/vriad/zod/blob/v2/package.json#L5

It seems that the main field in the package.json file was very recently changed from:

```
"main": "./lib/src/index.js",
```
to

```
"main": "[]]./lib/src/index.js",
```

### PR DESCRIPTION
**Pull request by marlonbernardes**
@vriad Not sure why this was changed in first place - perhaps it was an accident, as I'm unfamiliar with this syntax.

### CODE REVIEW

**Comment by pepakriz** [comment]
Bug introduced in https://github.com/vriad/zod/commit/31a8544d42e4f30aafd36a48d457c5cbf0018b6b

**Comment by vriad** [comment]
Whoops...weird. Thanks for the PR! Merged, fixed, and published to NPM.
