### ISSUE TITLE
v2 beta: Type 'Shape' does not satisfy the constraint 'ZodRawShape'

### ISSUE THREAD

**Issue by MajorBreakfast** [vriad/zod#180]
When compiling with `zod@2.0.0-beta.9` on TypeScript `4.0.3`, I get this error:

```
node_modules/zod/lib/src/helpers/partialUtil.d.ts(11,39): error TS2344: Type 'Shape' does not satisfy the constraint 'ZodRawShape'.
node_modules/zod/lib/src/helpers/partialUtil.d.ts(11,94): error TS2344: Type '{ [k in keyof Shape]: DeepPartial<Shape[k]>; }' does not satisfy the constraint 'ZodRawShape'.
  Type 'DeepPartial<Shape[k]>' is not assignable to type 'ZodTypeAny'.
    Type '{ object: Shape[k] extends ZodObject<infer Shape, infer Params, ZodTypeAny, { [k in keyof addQuestionMarks<{ [k in keyof infer Shape]: infer Shape[k]["_output"]; }>]: addQuestionMarks<...>[k]; }, { [k in keyof addQuestionMarks<...>]: addQuestionMarks<...>[k]; }> ? ZodOptional<...> : never; rest: ReturnType<...>; }[S...' is not assignable to type 'ZodType<any, any, any>'.
      Type '{ object: Shape[k] extends ZodObject<infer Shape, infer Params, ZodTypeAny, { [k in keyof addQuestionMarks<{ [k in keyof infer Shape]: infer Shape[k]["_output"]; }>]: addQuestionMarks<...>[k]; }, { [k in keyof addQuestionMarks<...>]: addQuestionMarks<...>[k]; }> ? ZodOptional<...> : never; rest: ReturnType<...>; }[S...' is not assignable to type 'ZodType<any, any, any>'.
        Type '{ object: Shape[k] extends ZodObject<infer Shape, infer Params, ZodTypeAny, { [k in keyof addQuestionMarks<{ [k in keyof infer Shape]: infer Shape[k]["_output"]; }>]: addQuestionMarks<...>[k]; }, { [k in keyof addQuestionMarks<...>]: addQuestionMarks<...>[k]; }> ? ZodOptional<...> : never; rest: ReturnType<...>; }[S...' is not assignable to type 'ZodType<any, any, any>'.
          Type '{ object: Shape[k] extends ZodObject<infer Shape, infer Params, ZodTypeAny, { [k in keyof addQuestionMarks<{ [k in keyof infer Shape]: infer Shape[k]["_output"]; }>]: addQuestionMarks<...>[k]; }, { [k in keyof addQuestionMarks<...>]: addQuestionMarks<...>[k]; }> ? ZodOptional<...> : never; rest: ReturnType<...>; }[S...' is not assignable to type 'ZodType<any, any, any>'.
            Type '(Shape[k] extends ZodObject<infer Shape, infer Params, ZodTypeAny, { [k in keyof addQuestionMarks<{ [k in keyof infer Shape]: infer Shape[k]["_output"]; }>]: addQuestionMarks<{ [k in keyof infer Shape]: infer Shape[k]["_output"]; }>[k]; }, { [k in keyof addQuestionMarks<...>]: addQuestionMarks<...>[k]; }> ? ZodOptio...' is not assignable to type 'ZodType<any, any, any>'.
              Type 'ReturnType<Shape[k]["optional"]>' is not assignable to type 'ZodType<any, any, any>'.
                Type 'unknown' is not assignable to type 'ZodType<any, any, any>'.
                  Type 'ReturnType<Shape[keyof Shape]["optional"]>' is not assignable to type 'ZodType<any, any, any>'.
                    Type 'unknown' is not assignable to type 'ZodType<any, any, any>'.
                      Type 'ReturnType<Shape[string | number | symbol]["optional"]>' is not assignable to type 'ZodType<any, any, any>'.
                        Type 'unknown' is not assignable to type 'ZodType<any, any, any>'.
                          Type 'ReturnType<Shape[string]["optional"]> | ReturnType<Shape[number]["optional"]> | ReturnType<Shape[symbol]["optional"]>' is not assignable to type 'ZodType<any, any, any>'.
                            Type 'ReturnType<Shape[string]["optional"]>' is not assignable to type 'ZodType<any, any, any>'.
                              Type 'unknown' is not assignable to type 'ZodType<any, any, any>'.
node_modules/zod/lib/src/helpers/partialUtil.d.ts(12,45): error TS2344: Type 'Shape[k]' does not satisfy the constraint 'ZodTypeAny'.
  Type 'Shape[keyof Shape]' is not assignable to type 'ZodType<any, any, any>'.
    Type 'Shape[string] | Shape[number] | Shape[symbol]' is not assignable to type 'ZodType<any, any, any>'.
      Type 'Shape[string]' is not assignable to type 'ZodType<any, any, any>'.
```

- `zod@1.11.9` compiles fine
- When looking at `node_modules/zod/lib/src/helpers/partialUtil.d.ts(11,39)` I see red squiggles in VS Code. I suspect it could be a type error in the library.

My `tsconfig.json`:
```
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2019",
    "strict": true,
    "outDir": "dist",
    "esModuleInterop": true
  },
  "include": ["src"]
}
```

**Comment by tnolli** [comment]
I have the same issue using typescript 3.9.7; it looks like the error is already fixed on the v2 branch, building a new version out of it does fix my issue.

@vriad are you planning to release a new beta version any soon? Do you need any help on it?

**Comment by tnolli** [comment]
> I have the same issue using typescript 3.9.7; it looks like the error is already fixed on the v2 branch, building a new version out of it does fix my issue.
> 
> @vriad are you planning to release a new beta version any soon? Do you need any help on it?

My previous comment is wrong, I have two projects, both created the same way using the same typescript version, one is working and the second one is raising the error.

It's enough to : ```import * as z from 'zod';``` without even use it, to have tsc complain in one project but not in the other

**Comment by max-mykhailenko** [comment]
PR works for me as well. @vriad please check

**Comment by max-mykhailenko** [comment]
@MajorBreakfast found that build works with "2.0.0-beta.5"

**Comment by marlonbernardes** [comment]
While the fix it not yet published you can set `skipLibCheck: true` in your tsconfig file.

This will still cause TypeScript to type-check the parts of the libraries that you actually use. 
Having said that, this is not an ideal long-term solution, as ideally I want all the libraries that I am using to compile successfully.

**Comment by vriad** [comment]
A fix has been merged in zod@2.0.0-beta.11. I had trouble reproducing the original issue so if someone could confirm that the build is working, that would be great. Leaving open until then.

**Comment by pepakriz** [comment]
@vriad I'd been facing the same issue and with zod@2.0.0-beta.12 everything works correctly. Thank you

**Comment by marlonbernardes** [comment]
I'm having a different error now:
Cannot find module `<...>/node_modules/zod/[]]./lib/src/index.js'`. 

Caused by this line:
https://github.com/vriad/zod/blob/v2/package.json#L5

**Comment by pepakriz** [comment]
@marlonbernardes Yep, now I'm facing the same issue as you've described. But it's not related to this issue. Can you create a new one, please?

**Comment by marlonbernardes** [comment]
@pepakriz I've created a new issue (#192) and opened a PR (#193) which should fix it.

**Comment by vriad** [comment]
Sorry for the delay on getting this fixed, I was moving across the US...long drive. 

The new issue was unrelated (typo by me!) and is also resolved.
